DjangoCrudApplication/DjangoCrudApplication/urls.py
"""
Definition of urls for DjangoCrudApplication.
"""

from datetime import datetime
from django.conf.urls import url, include
import django.contrib.auth.views as auth_views
from django.contrib import admin
admin.autodiscover()
from app.forms import authentication_forms
from app.views import main_views
from app.views import product_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# Examples:
urlpatterns = [
    url(r'', include('app.urls.product_urls')),
    url(r'^$', main_views.home, name='home'),
    url(r'^contact$', main_views.contact, name='contact'),
    url(r'^about$', main_views.about, name='about'),
    url(r'^login/$',auth_views.LoginView.as_view(template_name="app/login.html",
                                                                authentication_form = authentication_forms.BootstrapAuthenticationForm,
                                                                extra_context = 
                                                                {
                                                                    'title': 'Log in',
                                                                    'year': datetime.now().year
                                                                 }),name='login'),

    url(r'^logout$',auth_views.LogoutView.as_view(next_page = '/'),name='logout'),

   
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, documetn_root = settings.MEDIA_ROOT)

DjangoCrudApplication/app/models.py
"""
Definition of models.
"""

from django.db import models

# Create your models here.

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length = 100)
    price = models.DecimalField(max_digits = 9, decimal_places = 2)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product_name

DjangoCrudApplication/app/models/product.py
from django.db import models

# Create your models here.

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length = 100)
    price = models.DecimalField(max_digits = 9, decimal_places = 2)
    quantity = models.IntegerField()
    product_image = models.ImageField(max_length = 200,null=True)

    def __str__(self):
        return self.product_name

DjangoCrudApplication/app/forms/authentication_forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))

    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

DjangoCrudApplication/app/forms/product_forms.py
from app.models.product import Product
from django import forms

class ProductForm(forms.ModelForm):
    product_name = forms.CharField(error_messages={'required': 'Product Name is required!'},
                                   widget=forms.TextInput({'class': 'form-control','placeholder': 'Enter product name'}))
    price = forms.DecimalField(error_messages={'required': 'Product price is required!'},
                                   widget=forms.TextInput({'class': 'form-control','placeholder': 'Enter product price'}))
    quantity = forms.IntegerField(error_messages={'required': 'Product quantity is required!'},
                                   widget=forms.NumberInput({'class': 'form-control','placeholder': 'Enter product quantity'}))

    product_image = forms.ImageField(required=False)

    class Meta:
        model = Product
        fields = '__all__'

DjangoCrudApplication/app/views/main_views.py
"""
Definition of views.
"""

from django.shortcuts import render
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime

def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/index.html',
        {
            'title':'Home Page',
            'year':datetime.now().year,
        }
    )

def contact(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/contact.html',
        {
            'title':'Contact',
            'message':'Your contact page.',
            'year':datetime.now().year,
        }
    )

def about(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    
    return render(
        request,
        'app/about.html',
        {
            'title':'About',
            'message':'Your application description page.',
            'year':datetime.now().year,
        }
    )

DjangoCrudApplication/app/views/product_views.py
from django.shortcuts import render,redirect,get_object_or_404
from app.forms.product_forms import ProductForm
from app.models.product import Product
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime
from django.core.files.storage import FileSystemStorage

def product_list(request):
    assert isinstance(request, HttpRequest)
    products = Product.objects.all()
    return render(request,'product/product_list.html',
                  {
                      'title':'Product List',
                      'products' : products,
                      'year':datetime.now().year,
                  })

def create_product(request):
    assert isinstance(request, HttpRequest)
    form = ProductForm(request.POST or None)

    
    if request.method == "POST" and request.FILES.get('product_image'):
        myfile = request.FILES['product_image']
        product_to_be_created = request.POST.copy()
        product_to_be_created.update({'product_image': myfile.name})
        updated_form = ProductForm(data = product_to_be_created)
        if updated_form.is_valid():
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            updated_form.save()
            return redirect('products')

    return render(request,'product/create_product.html',
                  {
                      'form' : form,
                      'title':'Create Product',
                      'year':datetime.now().year,
                  })


def product_details(request,product_id):
    assert isinstance(request, HttpRequest)

    product = get_object_or_404(Product,product_id = product_id)

    return render(request,'product/product_details.html',
                  {
                      'product' : product,
                      'title':'Product Details',
                      'year':datetime.now().year,
                  })

def update_product(request,product_id):
    assert isinstance(request, HttpRequest)
    product = get_object_or_404(Product,product_id = product_id)

    form = ProductForm(request.POST or None, instance = product)

    if request.method == "POST":
        if form.is_valid():
           form.save()
           return redirect('products')

    return render(request,'product/update_product.html',
                  {
                      'form' : form,
                      'title':'Update Product',
                      'year':datetime.now().year,
                  })

def delete_product(request,product_id):
    assert isinstance(request, HttpRequest)
    product = get_object_or_404(Product,product_id = product_id)

    if request.method == "POST":
        product.delete()
        return redirect('products')

    return render(request,'product/delete_product.html',
                  {
                      'product' : product,
                      'title':'Delete Product',
                      'year':datetime.now().year,
                  })
    

DjangoCrudApplication/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>


{% endblock %}

DjangoCrudApplication/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

DjangoCrudApplication/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Django is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://www.djangobook.com/en/2.0/index.html">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.org/">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

DjangoCrudApplication/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/library/font-awesome/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Django Crud</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                    <li><a href="{% url 'products' %}">Products</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

DjangoCrudApplication/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal" novalidate>
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                
                <span class="validation-summary-errors">{{form.non_field_errors}}</span>
               
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                        <span class="text-danger">{{ form.errors.username | striptags }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                        <span class="text-danger">{{ form.errors.password | striptags }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

DjangoCrudApplication/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

DjangoCrudApplication/app/templates/product/create_product.html
{% extends "app/layout.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2><strong><i class="fa fa-plus" aria-hidden="true"></i> {{ title }}</strong></h2>
    </div>
    <form style="margin-bottom: 0" class="form-horizontal" method="post" enctype="multipart/form-data" novalidate>
        <div class="panel-body">
            {% csrf_token %}

            <div class="text-danger">{{ form.non_field_errors }}</div>

            <div class="form-group">
                <label for="id_product_name" class="col-md-2 control-label">Product Name</label>
                <div class="col-md-10">
                    {{ form.product_name }}
                    <span class="text-danger">{{ form.errors.product_name | striptags }}</span>
                </div>
                
            </div>
            
            <div class="form-group">
                <label for="id_price" class="col-md-2 control-label">Price</label>
                <div class="col-md-10">
                    {{ form.price }}
                    <span class="text-danger">{{ form.errors.price | striptags }}</span>
                </div>
            </div>
            
            <div class="form-group">
                <label for="id_quantity" class="col-md-2 control-label">Quantity</label>
                <div class="col-md-10">
                    {{ form.quantity }}
                    <span class="text-danger">{{ form.errors.quantity | striptags }}</span>
                </div>
            </div>
            
            <div class="form-group">
                <label for="id_product_image" class="col-md-2 control-label">Product Image</label>
                <div class="col-md-10">
                    <div class="form-control">
                        {{ form.product_image }}
                    </div>
                    <span class="text-danger">{{ form.errors.product_image | striptags }}</span>
                </div>
            </div>
         
        </div>
        
        <div class="panel-footer">
            <button class="btn btn-success" type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Create</button>
            <a class="btn btn-primary" href="{% url 'products' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back to List</a>
        </div>
    </form>
</div>


{% endblock %}

DjangoCrudApplication/app/templates/product/delete_product.html
{% extends "app/layout.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2><strong><i class="fa fa-trash-o" aria-hidden="true"></i> {{ title }}</strong></h2>
    </div>
    <div class="panel-body">
        <div class="alert alert-danger">
            <strong>Delete!</strong> Are you sure you want to delete this product?
        </div>
        <div class="form-horizontal">

            <div class="form-group">
                <label class="control-label col-sm-2">Product Name</label>
                <div class="col-sm-10">
                    <div class="form-control">
                        {{product.product_name}}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2">Price</label>
                <div class="col-sm-10">
                    <div class="form-control">
                        {{product.price}}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2">Quantity</label>
                <div class="col-sm-10">
                    <div class="form-control">
                        {{product.quantity}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
            <a class="btn btn-primary" href="{% url 'products' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back to List</a>
        </form>
    </div>
</div>

{% endblock %}

DjangoCrudApplication/app/templates/product/product_details.html
{% extends "app/layout.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2><strong><i class="fa fa-info-circle" aria-hidden="true"></i> {{ title }}</strong></h2>
    </div>
    <div class="panel-body">
        <div class="form-horizontal" >
            <div class="form-group">
                <label class="control-label col-sm-2" >Product Name</label>
                <div class="col-sm-10">
                    <div class="form-control">
                        {{product.product_name}}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" >Price</label>
                <div class="col-sm-10"> 
                    <div class="form-control">
                        {{product.price}}
                    </div>
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-sm-2" >Quantity</label>
                <div class="col-sm-10"> 
                    <div class="form-control">
                        {{product.quantity}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <a class="btn btn-success" href="{% url 'update_product' product.product_id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Update</a>
        <a class="btn btn-primary" href="{% url 'products' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back to List</a>
    </div>
</div>


{% endblock %}

DjangoCrudApplication/app/templates/product/product_list.html
{% extends "app/layout.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 style="display: inline-block"><strong><i class="fa fa-list" aria-hidden="true"></i> {{ title }}</strong></h2>
        <a class="btn btn-success pull-right" href="{% url 'create-product' %}"><i class="fa fa-plus" aria-hidden="true"></i> Create Product</a>
    </div>
    <div class="panel-body">
        <div style="overflow: auto">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Price (Tk.)</th>
                    <th>Quantity (Kg)</th>
                    <th class="text-center" style="min-width: 200px;">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                <tr>
                    <td>{{product.product_name}}</td>
                    <td>{{product.price}}</td>
                    <td>{{product.quantity}}</td>
                    <td class="text-center" style="width: 200px">
                        <a class="btn btn-xs btn-info" href="{% url 'product_details' product.product_id %}">Details</a>
                        <a class="btn btn-xs btn-primary" href="{% url 'update_product' product.product_id %}">Update</a>
                        <a class="btn btn-xs btn-danger" href="{% url 'delete_product' product.product_id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}

                {% if products.count == 0 %}
                <tr>
                    <td class="text-center" colspan="4">No product found in the database</td>
                </tr>
                {% endif %}

                </tbody>
            </table>
        </div>
        
    </div>
</div>

{% endblock %}

DjangoCrudApplication/app/templates/product/update_product.html
{% extends "app/layout.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2><strong><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{ title }}</strong></h2>
    </div>
    <form style="margin-bottom: 0" class="form-horizontal" method="post" novalidate>
        <div class="panel-body">
            {% csrf_token %}

            <div class="text-danger">{{ form.non_field_errors }}</div>

            <div class="form-group">
                <label for="id_product_name" class="col-md-2 control-label">Product Name</label>
                <div class="col-md-10">
                    {{ form.product_name }}
                    <span class="text-danger">{{ form.errors.product_name | striptags }}</span>
                </div>
                
            </div>
            
            <div class="form-group">
                <label for="id_price" class="col-md-2 control-label">Price</label>
                <div class="col-md-10">
                    {{ form.price }}
                    <span class="text-danger">{{ form.errors.price | striptags }}</span>
                </div>
            </div>
            
            <div class="form-group">
                <label for="id_quantity" class="col-md-2 control-label">Quantity</label>
                <div class="col-md-10">
                    {{ form.quantity }}
                    <span class="text-danger">{{ form.errors.quantity | striptags }}</span>
                </div>
            </div>
         
        </div>
        
        <div class="panel-footer">
            <button class="btn btn-success" type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Save</button>
            <a class="btn btn-primary" href="{% url 'products' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back to List</a>
        </div>
    </form>
</div>


{% endblock %}